pyms:
  requests:
    data: ""
  swagger:
    path: "swagger"
    file: "swagger.yaml"
  tracer:
    client: "jaeger"
    host: "localhost"
    component_name: "Python Microservice"
ms:
  DEBUG: false
  TESTING: false
  APP_NAME: Template
  APPLICATION_ROOT : /template
  SQLALCHEMY_TRACK_MODIFICATIONS: true
  SECRET_KEY: "gjr39dkjn344_!67#"
  DATABASE: db.sqlite3
  SQLALCHEMY_DATABASE_URI: sqlite:////microservice/database/db.sqlite3
